namespace:
  name: staging
 
image:
  repository: isildrum/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

containerPort: 3111

livenesProbe:
  path: /healthz

readinesProbe:
  path: /healthz

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
  
resources:
  requests:
    cpu: 300m
    memory: 90Mi

limits:
  requests:
    cpu: 500m
    memory: 128Mi

