namespace:
  name: sandbox
 
image:
  repository: isildrum/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

livenesProbe:
  path: /healthz

readinesProbe:
  path: /healthz

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
  
resources:
  requests:
    cpu: 250m
    memory: 64Mi

limits:
  requests:
    cpu: 500m
    memory: 128Mi

